QueryInstitute/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using QueryInstitute.Models;
using QueryInstitute.Repository.Contracts;
using System.Linq;

namespace QueryInstitute.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly IDepartmentRepository _departmentRepository;

        public CourseController(ICourseRepository courseRepository, IDepartmentRepository departmentRepository)
        {
            _courseRepository = courseRepository;
            _departmentRepository = departmentRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var courses = _courseRepository.CoursesToDeparment();
            return View(courses);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Dep = _departmentRepository.GetAll();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Course model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Dep = _departmentRepository.GetAll();
                return View(model);
            }

            _courseRepository.Add(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var course = _courseRepository.GetById(id);
            if (course == null)
            {
                return NotFound();
            }

            ViewBag.Dep = _departmentRepository.GetAll();
            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Course model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Dep = _departmentRepository.GetAll();
                return View(model);
            }

            _courseRepository.Update(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var course = _courseRepository.GetById(id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCourse(int CourseId)
        {
            var course = _courseRepository.GetById(CourseId);
            if (course == null)
            {
                return NotFound();
            }

            _courseRepository.Delete(course);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var course = _courseRepository.CoursesToDeparment().FirstOrDefault(x => x.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }
    }
}

QueryInstitute/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QueryInstitute.Models;
using System.Linq;
using System.Threading.Tasks;

namespace QueryInstitute.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.Select(s => new RoleViewModel
            {
                Id = s.Id,
                Name = s.Name
            }).ToListAsync();

            return View(roles);
        }

        public async Task<IActionResult> Details(string id)
        {
            var role = await _roleManager.FindByIdAsync(id ?? "0");
            if (role == null)
            {
                return NotFound();
            }

            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreatePost(RoleViewModel model)
        {
            if (model == null)
            {
                return NotFound();
            }

            if (await _roleManager.RoleExistsAsync(model.Name))
            {
                ModelState.AddModelError("", "Name is exist");
            }

            var role = new IdentityRole()
            {
                Name = model.Name
            };

            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }


        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(RoleViewModel model)
        {
            if (model == null)
            {
                return NotFound();
            }

            if (await _roleManager.RoleExistsAsync(model.Name))
            {
                ModelState.AddModelError("", "Name is exist");
            }

            var role = await _roleManager.FindByIdAsync(model.Id);
            role.Name = model.Name;
            role.NormalizedName = model.Name.ToUpper();
            await _roleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }



        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id ?? "0");
            if (role == null)
            {
                return NotFound();
            }

            var model = new RoleViewModel()
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(model);
        }


        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }

    }
}

QueryInstitute/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using QueryInstitute.Models;
using QueryInstitute.Repository.Contracts;
using System.Linq;

namespace QueryInstitute.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;
        private readonly IEnrollmentRepository _enrollmentRepository;
        private readonly ICourseRepository _coursesRepository;

        public StudentController(IStudentRepository studentRepository, IEnrollmentRepository enrollmentRepository, ICourseRepository coursesRepository)
        {
            _studentRepository = studentRepository;
            _enrollmentRepository = enrollmentRepository;
            _coursesRepository = coursesRepository;
        }

        public IActionResult Index(string sort, string searchString)
        {
            var students = _studentRepository.GetAll().Reverse();

            ViewData["sortName"] = "desc";
            if (sort == "asc")
            {
                ViewData["sortName"] = "desc";
                students = students.OrderByDescending(s => s.EnrollmentDate);
            }
            else if (sort == "desc")
            {
                ViewData["sortName"] = "asc";
                students = students.OrderBy(s => s.EnrollmentDate);
            }

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                ViewData["currentFilter"] = searchString;
                students = students.Where(s => s.FirstName.ToLower().Contains(searchString.ToLower())
                || s.LastName.ToLower().Contains(searchString.ToLower()));
            }

            return View(students);
        }

        public IActionResult Details(int id = 0)
        {
            ViewBag.Courses = _coursesRepository.GetAll();
            var student = _studentRepository.GetById(id);
            if (student == null)
            {
                return NotFound();
            }

            var model = new StudentViewModel()
            {
                Student = student,
                Enrollments = _studentRepository.CoursesToStudent(student.StudentId)

            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Student model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _studentRepository.Add(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var student = _studentRepository.GetById(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpPost, ActionName("Delete")]
        [AutoValidateAntiforgeryToken]
        public IActionResult DeletePost(int StudentId)
        {
            var student = _studentRepository.GetById(StudentId);
            if (student == null)
            {
                return NotFound();
            }

            _studentRepository.Delete(student);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var course = _studentRepository.GetById(id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Student model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _studentRepository.Update(model);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult AddCourseToStudent(StudentViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Enrollment.StudentId == 0 || model.Enrollment.CourseId == 0)
                {

                    return RedirectToAction("Index");
                }
                _enrollmentRepository.Add(model.Enrollment);
            };
            return RedirectToAction("Details", routeValues: new { id = model.Enrollment.StudentId });
        }
    }
}

QueryInstitute/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QueryInstitute.Models;
using System.Linq;
using System.Threading.Tasks;

namespace QueryInstitute.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.Select(s => new UserViewModel
            {
                Id = s.Id,
                Email = s.Email
            }).ToListAsync();

            return View(users);
        }

        public async Task<IActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _roleManager.Roles.ToListAsync();
            var userRoles = (await _userManager.GetRolesAsync(user)).ToList();

            var model = new UserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                UserInRoles = roles.Select(s => new RoleViewModel()
                {
                    Id = s.Id,
                    Name = s.Name,
                    Select = userRoles.Exists(x => x == s.Name)
                }).ToList()
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Details")]
        public async Task<IActionResult> Update(string id, UserViewModel model)
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == id);
            var roles = await _roleManager.Roles.ToListAsync();

            foreach (var role in model.UserInRoles)
            {

                if (role.Select)
                {
                    await _userManager.AddToRoleAsync(user, roles.FirstOrDefault(x => x.Id == role.Id)?.Name);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, roles.FirstOrDefault(x => x.Id == role.Id)?.Name);
                }
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
    }
}

QueryInstitute/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager;
@inject UserManager<IdentityUser> UserManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QueryInstitute</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">QInstitute</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @*<li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>*@
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Course" asp-action="Index">Courses <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Student" asp-action="Index">Students <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Department" asp-action="Index">Departments <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor <span class="sr-only">(current)</span></a>
                </li>
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Role" asp-action="Index">Roles <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users <span class="sr-only">(current)</span></a>
                    </li>
                }

            </ul>

            @if (!SignInManager.IsSignedIn(User))
            {
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Register <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            }
            else
            {
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ">
                        <i class="nav-link pt-2 mt-1">
                            @User.Identity.Name.ToUpper()
                        </i>
                    </li>
                    <li class="nav-item active">
                        <form class="nav-link" asp-controller="Account" asp-action="Logout">
                            <input type="submit" class="btn btn-sm btn-outline-success" value="Logout" />
                        </form>
                    </li>
                </ul>
            }
        </div>
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; QueryInstitute
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>